# Generated by Django 5.2.5 on 2025-08-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_user_first_name_remove_user_last_name_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Accepted', max_length=10)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_links', to='user.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_links', to='user.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['follower'], name='networking__followe_f361ba_idx'), models.Index(fields=['following'], name='networking__followi_643eb7_idx'), models.Index(fields=['status'], name='networking__status_9ae007_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_profile'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow_profile')],
            },
        ),
    ]
