# Generated by Django 5.2.5 on 2025-08-28 19:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_first_name_remove_user_last_name_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['-created_at'], name='user_profil_created_02cd15_btree'),
        ),
    ]
