# Generated by Django 5.2.5 on 2025-08-29 16:53

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post_tags_alter_post_author_alter_post_content_and_more'),
        ('user', '0003_profile_user_profil_created_02cd15_btree'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('content', models.TextField(max_length=5000, verbose_name='content')),
                ('media', models.ImageField(blank=True, null=True, upload_to=content.models.post_image_path, verbose_name='media')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='user.profile', verbose_name='author')),
                ('tags', models.ManyToManyField(blank=True, related_name='scheduled_posts', to='content.tag', verbose_name='tags')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['author', 'scheduled_at'], name='content_sch_author__f2bff7_idx')],
            },
        ),
    ]
