# Generated by Django 5.2.5 on 2025-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_scheduledpost'),
        ('user', '0003_profile_user_profil_created_02cd15_btree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='scheduledpost',
            name='tags',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='content_pos_author__ebea4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='content_pos_created_415459_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='content_tag_name_52ccf1_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_task_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('canceled', 'Canceled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['-created_at'], name='post_published_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['author', '-created_at'], name='post_published_author_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('status', 'scheduled')), fields=['author', 'scheduled_at'], name='post_scheduled_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_post_author_title'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scheduled_at__isnull', False), ('status', 'scheduled')), models.Q(models.Q(('status', 'scheduled'), _negated=True), ('scheduled_at__isnull', True)), _connector='OR'), name='scheduled_requires_time'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', True)), _connector='OR'), name='published_requires_time'),
        ),
        migrations.DeleteModel(
            name='ScheduledPost',
        ),
    ]
